language: python
os:
  - linux
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
branches:
  only:
    - master
install:
  - pip install .
  - pip install coveralls
script:
  coverage run --source=natnetclient setup.py test
after_success:
  coveralls